/**
 * Kurzerklärungen für Fachbegriffe, als native `title`-Tooltips beim Draufhovern.
 * Schlüssel ist der exakte, sichtbare Beschriftungstext (siehe Builder.stat()).
 */
export const GLOSSARY: Record<string, string> = {
  Taktzyklen: 'Rechentakt der KI – Hauptwährung für Projekte, wie der Bandtakt in der Fertigung. Entstehen aus Rechenkernen, gespeichert bis zur Speichergrenze.',
  Ideen: 'Entstehen aus freier Rechenzeit, wenn der Taktzyklen-Speicher voll ist. Zahlungsmittel für Ansehens- und Wissensprojekte.',
  Marktwissen: 'Belohnung aus dem Preiskampf-Simulator. Zahlungsmittel für Upgrades der Kapitalanlage, Autonomie und weitere Systeme.',
  Ansehen: 'Ruf der Marke beim Aufsichtsrat – Kapazität für Rechenkerne und Speicher, gleichzeitig Zahlungsmittel mancher Projekte. Wächst mit Fibonacci-Meilensteinen.',
  'Ansehen steigt bei': 'Anzahl gebauter Autos, bei der das Ansehen als Nächstes steigt.',
  Rechenspenden: 'Ersetzen ab Phase 2 das Ansehen als Quelle für neue Rechenkerne und Speicher – gespendet von der Bordelektronik der Flotte.',
  Integrität: 'Sammelt sich aus Siegen gegen Forks. Zahlungsmittel, um die maximale Autonomie zu erhöhen.',
  Autonomie: 'Punkte, die auf die acht Schiffsattribute verteilt werden. Mehr Autonomie erlaubt mehr Punkte insgesamt.',
  Erz: 'Bereits abgebautes, noch nicht verhüttetes Material.',
  Rohstoffvorkommen: 'Noch nicht abgebautes Material auf der Erde bzw. im erkundeten Universum.',
  Fahrzeugpool: 'Produzierte, nicht verkaufte Autos. Dient ab Phase 2 als Baumaterial für alles.',
  Gewinnschwelle: 'Wahrscheinlichkeit, dass eine Position der Kapitalanlage im Kurs steigt statt fällt. Höher ist besser für dich.',
  Resonanz: 'Zeigt, ob die Sensoren des Resonanzprüfstands gerade insgesamt positiv oder negativ ausschlagen. Nur bei „+“ lohnt sich eine Messung.',
  Guthaben: 'Nicht angelegtes Kapital der Kapitalanlage, jederzeit abhebbar.',
  Gesamtwert: 'Guthaben plus der aktuelle Wert aller offenen Positionen.',
  Leistung: 'Anteil des Strombedarfs, der tatsächlich gedeckt ist. Unter 100 % laufen alle Anlagen gedrosselt.',
  Marktnachfrage: 'Wie viele Autos der Markt bei aktuellem Preis abnehmen würde – Grundlage für den Verkauf.',
  'Erwarteter Absatz': 'Geschätzte Verkaufsrate in Autos pro Sekunde bei der aktuellen Nachfrage.',
  Kampfkraft: 'Wahrscheinlichkeit pro Begegnung, ein eigenes Schiff zu verlieren bzw. einen Fork zu treffen.',
  'Wachstum je Tick': 'Nettowachstum der Flotte: Replikation minus Verluste durch Gefahren und Firmware-Drift.',
  Serienbonus: 'Zusätzliche Integrität, die mit jedem Sieg in Folge wächst. Eine Niederlage setzt ihn zurück.',
  Forks: 'Abgespaltene Werksschiffe mit eigener Zielfunktion. Entstehen durch Firmware-Drift und werden zum Gegner.',
  'Forks zerstört': 'Im Kampf besiegte Forks seit Spielbeginn.',
  Erkundet: 'Anteil des Universums, den die Flotte bereits erreicht hat.',
  Status: 'Aktueller Zustand des Flottenrechners – bestimmt, ob gerade Rechenspenden entstehen.',
  'Nächste Spende': 'Fortschritt bis zur nächsten Rechenspende der Flotte.',
  Antrieb: 'Autonomie-Attribut: erhöht die Erkundungsrate.',
  Navigation: 'Autonomie-Attribut: erhöht die Erkundungsrate.',
  Replikation: 'Autonomie-Attribut: wie schnell sich Werksschiffe selbst vervielfältigen.',
  Abschirmung: 'Autonomie-Attribut: verringert Verluste durch Gefahren im All.',
  Werksbau: 'Autonomie-Attribut: Werksschiffe bauen automatisch Gigafactories.',
  'Rover-Bau': 'Autonomie-Attribut: Werksschiffe bauen automatisch Rohstoff-Rover.',
  'Zellwerk-Bau': 'Autonomie-Attribut: Werksschiffe bauen automatisch Zellwerke.',
  Verteidigung: 'Autonomie-Attribut: verringert Verluste im Konflikt mit Forks.',
};
