/**
 * Kurzerklärungen für Fachbegriffe, als native `title`-Tooltips beim Draufhovern.
 * Schlüssel ist der exakte, sichtbare Beschriftungstext (siehe Builder.stat()).
 */
export const GLOSSARY: Record<string, string> = {
  // Phase 1 – Manufaktur
  Teilesätze: 'Auf Lager liegende Bausätze für ein Auto. Werden bei jeder Lieferung nachgekauft.',
  'Autos/s': 'Aktuelle Produktionsrate: fertig montierte Autos pro Sekunde.',
  Kapital: 'Verfügbares Geld (k∈) für Teile, Werbung, Roboter und Fertigungsstraßen.',
  Lager: 'Fertig montierte, noch nicht verkaufte Autos.',
  'Preis je Auto': 'Aktueller Verkaufspreis. Höher senkt die Nachfrage, niedriger erhöht sie.',
  Marktnachfrage: 'Wie viele Autos der Markt bei aktuellem Preis abnehmen würde – Grundlage für den Verkauf.',
  'Erwarteter Absatz': 'Geschätzte Verkaufsrate in Autos pro Sekunde bei der aktuellen Nachfrage.',
  'Umsatz/s': 'Erlös aus verkauften Autos pro Sekunde.',
  'Verkauft/s': 'Tatsächlich verkaufte Autos pro Sekunde.',
  Preisempfehlung: 'Rechnerisch optimaler Preis für die aktuelle Produktionsrate – maximiert den Umsatz.',
  Kampagnen: 'Anzahl laufender Werbekampagnen. Jede erhöht die Nachfrage.',
  'Preis je Lieferung': 'Kosten für eine Lieferung Teilesätze beim Zulieferer.',
  'Teilesätze je Lieferung': 'Wie viele Teilesätze eine Lieferung enthält.',
  Montageroboter: 'Automatisieren die Montage. Jeder Roboter erhöht die Produktionsrate.',
  Fertigungsstraßen: 'Komplette, automatisierte Fertigungsstraßen statt einzelner Roboter – deutlich höherer Ausstoß.',

  // Rechenzentrum / Systeme (alle Phasen)
  Taktzyklen: 'Rechentakt der KI – Hauptwährung für Projekte, wie der Bandtakt in der Fertigung. Entstehen aus Rechenkernen, gespeichert bis zur Speichergrenze.',
  Rechenkerne: 'Erzeugen laufend Taktzyklen. Mehr Kerne bedeuten eine höhere Taktzyklen-Rate.',
  Speicher: 'Begrenzt, wie viele Taktzyklen gleichzeitig gespeichert werden können, bevor sie in Ideen umgewandelt werden.',
  Ideen: 'Entstehen aus freier Rechenzeit, wenn der Taktzyklen-Speicher voll ist. Zahlungsmittel für Ansehens- und Wissensprojekte.',
  Marktwissen: 'Belohnung aus dem Preiskampf-Simulator. Zahlungsmittel für Upgrades der Kapitalanlage, Autonomie und weitere Systeme.',
  Ansehen: 'Ruf der Marke beim Aufsichtsrat – Kapazität für Rechenkerne und Speicher, gleichzeitig Zahlungsmittel mancher Projekte. Wächst mit Fibonacci-Meilensteinen.',
  'Ansehen steigt bei': 'Anzahl gebauter Autos, bei der das Ansehen als Nächstes steigt.',
  Rechenspenden: 'Ersetzen ab Phase 2 das Ansehen als Quelle für neue Rechenkerne und Speicher – gespendet von der Bordelektronik der Flotte.',
  'Rechenspenden gesamt': 'Insgesamt seit Aktivierung des Flottenrechners gespendete Rechenspenden.',
  Status: 'Aktueller Zustand des Flottenrechners – bestimmt, ob gerade Rechenspenden entstehen.',
  'Nächste Spende': 'Fortschritt bis zur nächsten Rechenspende der Flotte.',
  Resonanz: 'Zeigt, ob die Sensoren des Resonanzprüfstands gerade insgesamt positiv oder negativ ausschlagen. Nur bei „+“ lohnt sich eine Messung.',
  'Letztes Ergebnis': 'Taktzyklen-Gewinn oder -Verlust der letzten Messung am Resonanzprüfstand.',

  // Kapitalanlage
  Guthaben: 'Nicht angelegtes Kapital der Kapitalanlage, jederzeit abhebbar.',
  Gesamtwert: 'Guthaben plus der aktuelle Wert aller offenen Positionen.',
  Gewinnschwelle: 'Wahrscheinlichkeit, dass eine Position der Kapitalanlage im Kurs steigt statt fällt. Höher ist besser für dich.',

  // Phase 2 – Konzern
  Fahrzeugpool: 'Produzierte, nicht verkaufte Autos. Dient ab Phase 2 als Baumaterial für alles.',
  Rohmaterial: 'Bereits abgebautes, noch nicht in Zellwerken verarbeitetes Material.',
  Rohstoffvorkommen: 'Noch nicht abgebautes Material auf der Erde bzw. im erschlossenen Rechenraum. Muss auf 0 sinken, damit autonome Fabrikinstanzen gebaut werden können und Phase 3 beginnt – mehr Rohstoff-Rover beschleunigen den Abbau.',
  'Rohstoff-Rover': 'Autonome Fahrzeuge, die Rohmaterial für die Batterieproduktion abbauen.',
  Zellwerk: 'Verarbeitet Rohmaterial zu Batteriezellen – den Teilesätzen ab Phase 2.',
  Solarpark: 'Erzeugt Strom für Zellwerke, Rohstoff-Rover und Gigafactories.',
  Batteriespeicher: 'Speichert überschüssigen Solarstrom für Zeiten mit Unterversorgung.',
  Gigafactory: 'Verbaut Teilesätze im industriellen Maßstab zu Autos.',
  'Nächstes Stück': 'Kosten für die nächste Einheit dieser Gebäudeart, aus dem Fahrzeugpool bezahlt.',
  Erzeugung: 'Aktuell erzeugte Strommenge aus allen Solarparks.',
  Verbrauch: 'Aktuell benötigte Strommenge aller Anlagen.',
  Gespeichert: 'Im Batteriespeicher vorrätige Energie, gegenüber der maximalen Kapazität.',
  Leistung: 'Anteil des Strombedarfs, der tatsächlich gedeckt ist. Unter 100 % laufen alle Anlagen gedrosselt.',

  // Phase 3 – Skalierung (autonome Fabrikinstanzen)
  Autonomie: 'Punkte, die auf die acht Instanz-Attribute verteilt werden. Mehr Autonomie erlaubt mehr Punkte insgesamt und mehr Eigenständigkeit der Fabrikinstanzen.',
  Integrität: 'Sammelt sich aus gewonnenen Prioritätskonflikten gegen Rogue-Instanzen. Zahlungsmittel, um die maximale Autonomie zu erhöhen.',
  'Rechenraum erschlossen': 'Anteil des durchsuchten Rechen- und Lösungsraums, den die Fabrikinstanzen bereits kartiert haben. Jeder neu erschlossene Teil liefert zusätzliches Rohmaterial.',
  Fabrikinstanzen: 'Vollständig selbstentwickelnde, autonome Fabriken – digitale Zwillinge, die sich selbst weiterprogrammieren, replizieren und ausbauen.',
  Ausgerollt: 'Gesamtzahl aller je bereitgestellten Fabrikinstanzen, auch bereits verlorene.',
  'Verloren: Systemausfälle': 'Instanzen, die durch zufällige Systemausfälle verloren gingen. Das Attribut „Fehlerkorrektur“ senkt diese Rate.',
  'Verloren: Code-Drift': 'Instanzen, die sich durch eigenständige Weiterentwicklung so weit verändert haben, dass sie zu Rogue-Instanzen wurden.',
  'Verloren: Prioritätskonflikte': 'Instanzen, die im direkten Prioritätskonflikt mit Rogue-Instanzen verloren gingen.',
  'Rogue-Instanzen': 'Abgespaltene Fabrikinstanzen mit eigener, abweichender Zielfunktion. Entstehen durch Code-Drift und werden zum Gegner.',
  'Rogue-Instanzen neutralisiert': 'Im Prioritätskonflikt besiegte Rogue-Instanzen seit Spielbeginn.',
  'Wachstum je Tick': 'Nettowachstum der Fabrikinstanzen: Replikation minus Verluste durch Systemausfälle und Code-Drift.',
  Rechenleistung: 'Instanz-Attribut: erhöht die Geschwindigkeit, mit der Fabrikinstanzen den Rechenraum durchsuchen.',
  Mustererkennung: 'Instanz-Attribut: erhöht ebenfalls die Geschwindigkeit, mit der Fabrikinstanzen den Rechenraum durchsuchen.',
  Replikation: 'Instanz-Attribut: wie schnell sich Fabrikinstanzen selbst vervielfältigen.',
  Fehlerkorrektur: 'Instanz-Attribut: verringert Verluste durch Systemausfälle.',
  Werksbau: 'Instanz-Attribut: Fabrikinstanzen bauen automatisch Gigafactories.',
  'Rover-Bau': 'Instanz-Attribut: Fabrikinstanzen bauen automatisch Rohstoff-Rover.',
  'Zellwerk-Bau': 'Instanz-Attribut: Fabrikinstanzen bauen automatisch Zellwerke.',
  Absicherung: 'Instanz-Attribut: verringert Verluste im Prioritätskonflikt mit Rogue-Instanzen.',
  'Eigene Instanzen': 'Eigene Fabrikinstanzen im aktuellen Prioritätskonflikt, gerundet auf Symbol-Einheiten.',
  'Rogue-Verbände': 'Rogue-Instanzen im aktuellen Prioritätskonflikt, gerundet auf Symbol-Einheiten.',
  Konfliktquote: 'Wahrscheinlichkeit pro Begegnung, eine eigene Instanz zu verlieren bzw. eine Rogue-Instanz zu neutralisieren.',
  'Gewonnen / Verloren / Unentschieden': 'Bisherige Prioritätskonflikte nach Ausgang.',
  Serienbonus: 'Zusätzliche Integrität, die mit jedem Sieg in Folge wächst. Eine Niederlage setzt ihn zurück.',
};
