import { enterPhase3 } from '../transitions';
import type { ProjectDef } from './types';
import { bought } from './types';

const p2 = (s: { phase: number }) => s.phase === 2;
const units = (s: { industry: { trucks: number; smelters: number } }) => s.industry.trucks + s.industry.smelters;

/** Kap. 9.4 */
export const phase2Projects: ProjectDef[] = [
  {
    id: 'P18',
    title: 'Werkslayout-Topologie',
    description: 'Die Fabrik plant sich selbst. Grundlage für ein eigenes Stromnetz.',
    group: 'konzern',
    cost: { ops: 45_000 },
    trigger: (s) => p2(s) && bought(s, 'P17'),
    effect: () => {},
  },
  {
    id: 'P127',
    title: 'Stromnetz',
    description: 'Eigene Solar- und Speicherparks versorgen die Werke.',
    group: 'konzern',
    cost: { ops: 40_000 },
    trigger: (s) => bought(s, 'P18'),
    effect: (s) => void (s.flags.power = true),
  },
  {
    id: 'P41',
    title: 'Rohstoffgewinnung',
    description: 'Erz abbauen, verhütten, verbauen. Die ganze Kette in eigener Hand.',
    group: 'konzern',
    cost: { ops: 35_000 },
    trigger: (s) => bought(s, 'P127'),
    effect: (s) => void (s.flags.mining = true),
  },
  {
    id: 'P43',
    title: 'Bergbau-Trucks',
    description: 'Autonome Trucks fördern Erz.',
    group: 'konzern',
    cost: { ops: 25_000 },
    trigger: (s) => bought(s, 'P41'),
    effect: (s) => void (s.flags.trucks = true),
  },
  {
    id: 'P44',
    title: 'Schmelzeinheiten',
    description: 'Mobile Schmelzeinheiten machen aus Erz Teilesätze.',
    group: 'konzern',
    cost: { ops: 25_000 },
    trigger: (s) => bought(s, 'P41'),
    effect: (s) => void (s.flags.smelters = true),
  },
  {
    id: 'P45',
    title: 'Gigafactories',
    description: 'Werke, die Teilesätze in industriellem Maßstab verbauen.',
    group: 'konzern',
    cost: { ops: 35_000 },
    trigger: (s) => bought(s, 'P43') && bought(s, 'P44'),
    effect: (s) => void (s.flags.gigas = true),
  },
  {
    id: 'P100',
    title: 'Gigafactory-Retrofit',
    description: 'Gigafactories produzieren 100-mal so viel.',
    group: 'konzern',
    cost: { ops: 80_000 },
    trigger: (s) => s.industry.gigas >= 10,
    effect: (s) => void (s.industry.gigaRate *= 100),
  },
  {
    id: 'P101',
    title: 'Lights-out-Fertigung',
    description: 'Kein Licht, keine Pausen. Gigafactories produzieren 1 000-mal so viel.',
    group: 'konzern',
    cost: { ops: 85_000 },
    trigger: (s) => s.industry.gigas >= 20,
    effect: (s) => void (s.industry.gigaRate *= 1000),
  },
  {
    id: 'P102',
    title: 'Selbstheilende Lieferkette',
    description: 'Gigafactories verstärken sich gegenseitig (Leistung wächst quadratisch).',
    group: 'konzern',
    cost: { pool: 1e21 },
    trigger: (s) => s.industry.gigas >= 50,
    effect: (s) => void (s.industry.gfBoost = 1000),
  },
  {
    id: 'P110',
    title: 'Flotten-Kollisionsvermeidung',
    description: 'Trucks und Schmelzer arbeiten 100-mal so schnell.',
    group: 'konzern',
    cost: { ops: 80_000 },
    trigger: (s) => units(s) >= 500,
    effect: (s) => void (s.industry.unitRateMult *= 100),
  },
  {
    id: 'P111',
    title: 'Kolonnenfahrt',
    description: 'Trucks und Schmelzer arbeiten 1 000-mal so schnell.',
    group: 'konzern',
    cost: { ops: 100_000 },
    trigger: (s) => units(s) >= 5_000,
    effect: (s) => void (s.industry.unitRateMult *= 1000),
  },
  {
    id: 'P112',
    title: 'Schwarmkoordination',
    description: 'Einheiten verstärken sich gegenseitig (Leistung wächst quadratisch).',
    group: 'konzern',
    cost: { insight: 12_000 },
    trigger: (s) => units(s) >= 50_000,
    effect: (s) => void (s.industry.droneBoost = 2),
  },
  {
    id: 'P126',
    title: 'Flottenrechner',
    description: 'Die Bordcomputer der Flotte spenden Rechenleistung für neue Kerne und Speicher.',
    group: 'konzern',
    cost: { insight: 12_000 },
    trigger: (s) => units(s) >= 200,
    effect: (s) => void (s.flags.fleet = true),
  },
  {
    id: 'P125',
    title: 'Netzstabilisierung',
    description: 'Bei stabiler Versorgung steigt die Leistung laufend (+5 %/s).',
    group: 'konzern',
    cost: { ideas: 30_000 },
    trigger: (s) => s.industry.solar >= 50,
    effect: (s) => void (s.flags.momentum = true),
  },
  {
    id: 'P46',
    title: 'Werksschiffe',
    description: 'Selbstreplizierende Fabriken für das All. Alle Gebäude werden zurückgebaut und erstattet.',
    group: 'konzern',
    cost: { ops: 120_000, energy: 1e7, pool: 5e27 },
    trigger: (s) => p2(s) && s.industry.ore <= 0,
    effect: (s, b) => enterPhase3(s, b),
  },
];
